name = "LeanUniverses"
version = "0.1.0"
defaultTargets = ["leanuniverses"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.20.1"

[[lean_lib]]
name = "LeanUniverses"

[[lean_exe]]
name = "leanuniverses"
root = "Main"
